/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

import java.io.*;
import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int a;
        int b;
    }
}
