/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;

public class Main {
    public static void main(String[] args) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(System.out));

        int[] doHomeworks = new int[28];
        for(int i = 0; i < doHomeworks.length; i++){
            doHomeworks[i] = Integer.parseInt(br.readLine());
        }

        Arrays.sort(doHomeworks);

        int count = 1;
        ArrayList<Integer> notHomeworks = new ArrayList<Integer>();

        for(int doHomework : doHomeworks){
            if(doHomework != count){
                while (doHomework == count){
                    notHomeworks.add(count);
                    System.out.printf("doHomework : %d, count : %d \n", doHomework, count);
                    System.out.println(notHomeworks);
                }
            }else {
                count++;
            }
        }
//
//        for (int notHomework : notHomeworks){
//            bw.write(notHomework + " ");
//        }
        bw.flush();
    }
}