/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

import java.io.*;
import java.util.Arrays;
import java.util.StringTokenizer;

public class Main {
    public static void main(String[] args) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(System.out));
        StringTokenizer st;

        int n = 0;
        int m = 0;

        st = new StringTokenizer(br.readLine());
        n = Integer.parseInt(st.nextToken());
        m = Integer.parseInt(st.nextToken());

        int[] box = new int[n];
        for (int x = 0; x < n; x++) {
            box[x] = x + 1;
        }

        for (int x = 0; x < m; x++) {
            st = new StringTokenizer(br.readLine());

            int i = Integer.parseInt(st.nextToken());
            int j = Integer.parseInt(st.nextToken());
            System.out.println(i);
            System.out.println(j);

            for (int y = j; y > i; y--) {
                System.out.printf("box[%d] : %d \n", y - 1, box[y - 1]);
                int keeping = box[y - 1];
                box[i] = box[y];
                box[y] = keeping;
                System.out.println(Arrays.toString(box));
            }
        }

        bw.flush();
    }
}